function [varargout] = insert_calibrationparameter(conn, station, idcalibration, name, value)

%INSERT_CALIBRATIONPARAMETER   Insert a new tuple in the tables
%calibrationparameter and calibrationvalue
%   INSERT_CALIBRATIONPARAMETER(idcalibration, name, value)
%   inserts the tuple identified by an autonumeric generated by MySQL.
%
%   Input:
%   conn: Database connection which must have been previously created.
%	station: is the name of the station.
%   idcalibration: numeric id of the calibration.
%   name: is the name of the parameter.
%   value: matrix that contains the actual value.
%
%   Output:
%   varargout: The output argument might or might not be present, if it
%   is, means the status of the transaction. 0 if the insertion was
%   successful, 1 otherwise.
%
%   Example:
%       insert_calibrationparameter(conn, 12, 'H', [12 23 3; 5 7 8])
%

% Written by 
% Sebastian Munera Alvarez and 
% Cesar Augusto Cartagena Ocampo 
% for the HORUS Project
% Universidad Nacional de Colombia
%   Copyright 2011 HORUS
%   $Date: 2011/07/27 16:15 $

try
    station = upper(station);
    if nargout==1
        varargout(1)={1};
    end
    
    % Insert in the database
    
    %reboot connection to the database if necessary
    [conn status] = renew_connection_db(conn);
    
    if status == 1
        return
    end
    
    try
        % Data for insertion in calibrationparameter
        newid  = generate_autoinc(conn, ['calibrationparameter_' station], ...
            'id', station);
        
        colnames = {'id', 'calibration', 'name'};
        extdata = {newid, idcalibration, name};
        
        fastinsert(conn, ['calibrationparameter_' station], colnames, extdata);
        
        % Insertion in calibrationvalue
        
        [m, n] = size(value);
        % Every matrix element is inserted as an independent row
        for r = 1:m
            for c = 1:n
                colnames = {'idparam', 'idcol', 'idrow', 'value'};
                extdata = {newid, c, r, value(r, c)};
                
                fastinsert(conn, ['calibrationvalue_' station], colnames, extdata);
            end
        end
        if nargout==1
            varargout(1)={0};
        end
        
    catch e
        disp([dberror('insert') e.message]);
    end
    
catch e
    disp(e.message)
end