function valid = validoptions(table)

%VALIDOPTIONS   Retrieve database table attributes.
%   valid = VALIDOPTIONS(table) retrieves all the attibutes corresponding
%   to the entity named 'table'. Currently, the available tables are:
%
%      'image', 'imagetype', 'rectifiedimage', 'mergedimage',
%      'obliqueimage', 'fusion', 'camerabyfusion', 'fusionparameter',
%      'fusionvalue', 'camera', 'station', 'calibration', 'timestack',
%      'roi', 'roicoordinate', 'calibrationparameter', 'calibrationvalue',
%      'gcp', 'pickedgcp', 'sensor', 'measurement', 'measurementtype',
%      'measurementvalue', 'commonpoint' and 'automaticparams'
%
%   Output:
%   valid: contains a list of the available attibutes for the specified
%   table.
%
%   See also ISVALIDOPTION.

% Written by 
% Sebastian Munera Alvarez and 
% Cesar Augusto Cartagena Ocampo 
% for the HORUS Project
% Universidad Nacional de Colombia
%   Copyright 2011 HORUS
%   $Date: 2011/07/21 15:52 $

try
    
    valid = cell(0);
    
    switch table
        case 'image'
            valid = {'filename', ...
                'type', ...
                'timestamp', ...
                'ismini', ...
                'path'};
            
        case 'imagetype'
            valid = {'idtype', ...
                'name', ...
                'description'};
            
        case 'rectifiedimage'
            valid = {'filename', ...
                'calibration'};
            
        case 'mergedimage'
            valid = {'filename', ...
                'idfusion'};
            
        case 'obliqueimage'
            valid = {'filename', ...
                'camera', ...
                'station'};
            
        case 'fusion'
            valid = {'id', ...
                'timestamp', ...
                'type'};
            
        case 'camerabyfusion'
            valid = {'idfusion', ...
                'camera', ...
                'station', ...
                'sequence'};
            
        case 'fusionparameter'
            valid = {'id', ...
                'idfusion', ...
                'name'};
            
        case 'commonpoint'
            valid = {'idfusion', ...
                'camera', ...
                'station', ...
                'name', ...
                'u', ...
                'v'};
            
        case 'fusionvalue'
            valid = {'idmatrix', ...
                'idcol', ...
                'idrow', ...
                'value'};
            
        case 'camera'
            valid = {'id', ...
                'station', ...
                'reference', ...
                'sizeX', ...
                'sizeY'};
            
        case 'station'
            valid = {'name', ...
                'elevation', ...
                'lat', ...
                'lon', ...
                'country', ...
                'state', ...
                'city', ...
                'responsible', ...
                'description'};
            
        case 'calibration'
            valid = {'idcalibration', ...
                'camera', ...
                'station', ...
                'timestamp', ...
                'resolution', ...
                'EMCuv', ...
                'EMCxy', ...
                'NCE'};
            
        case 'timestack'
            valid = {'filename', ...
                'camera', ...
                'station', ...
                'inittime', ...
                'path', ...
                'fps', ...
                'numFrames'};
            
        case 'roi'
            valid = {'idroi', ...
                'idcalibration', ...
                'type', ...
                'timestamp'};
            
        case 'roicoordinate'
            valid = {'idroi', ...
                'idcoord', ...
                'u', ...
                'v'};
            
        case 'calibrationparameter'
            valid = {'id', ...
                'calibration', ...
                'name'};
            
        case 'calibrationvalue'
            valid = {'idparam', ...
                'idcol', ...
                'idrow', ...
                'value'};
            
        case 'gcp'
            valid = {'idgcp', ...
                'station', ...
                'name', ...
                'x', ...
                'y', ...
                'z'};
            
        case 'pickedgcp'
            valid = {'calibration', ...
                'gcp', ...
                'station', ...
                'u', ...
                'v'};
            
        case 'sensor'
            valid = {'name', ...
                'station', ...
                'x', ...
                'y', ...
                'z', ...
                'isvirtual', ...
                'description'};
            
        case 'measurement'
            valid = {'idmeasurement', ...
                'type', ...
                'timestamp'};
            
        case 'measurementtype'
            valid = {'id', ...
                'sensor', ...
                'station', ...
                'paramname', ...
                'datatype', ...
                'unitx', ...
                'unity', ...
                'unitz', ...
                'axisnamex', ...
                'axisnamey', ...
                'axisnamez', ...
                'description'};
            
        case 'measurementvalue'
            valid = {'idmeasurement', ...
                'idcol', ...
                'idrow', ...
                'iddepth', ...
                'value'};
            
        case 'automaticparams'
            valid = {'idauto', ...
                'station', ...
                'type', ...
                'start_hour', ...
                'start_minute', ...
                'end_hour', ...
                'end_minute', ...
                'step', ...
                'duration',...
                'num_images'};
            
        otherwise
            disp(dberror('args'));
    end
    
catch e
    disp(e.message)
end